# Generated by Django 4.2.11 on 2024-04-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "pk_NumeroCommande",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("Annee", models.IntegerField()),
                ("Budget", models.CharField(max_length=7)),
                (
                    "Financement",
                    models.CharField(
                        choices=[("Ville", "Ville"), ("Etat", "Etat")], max_length=50
                    ),
                ),
                (
                    "TypeVehicule",
                    models.CharField(
                        choices=[
                            ("VL", "VL"),
                            ("PL", "PL"),
                            ("VU", "VU"),
                            ("2R", "2R"),
                            ("Bateau", "Bateau"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Categorie", models.CharField(max_length=50)),
                ("Designation", models.CharField(max_length=100)),
                ("EtatSignatureCommandeAchat", models.CharField(max_length=50)),
                ("DateCommandeVenteDILT", models.DateField()),
                ("EngagementJuridique", models.CharField(max_length=50)),
                ("NumeroARC", models.CharField(max_length=50)),
                ("DateCommandeVente", models.DateField()),
                ("Direction", models.CharField(max_length=100)),
                ("SousDirection", models.CharField(max_length=100)),
                ("ServiceAffectation", models.CharField(max_length=100)),
                ("EspacePieceJointe", models.BinaryField()),
                ("Commentaire", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RenseignementVhFils",
            fields=[
                (
                    "NumeroSerie",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("CodeArticle", models.CharField(max_length=100)),
                ("NumeroImmatriculation", models.CharField(max_length=100)),
                (
                    "TypeVehicule",
                    models.CharField(
                        choices=[
                            ("VL", "VL"),
                            ("PL", "PL"),
                            ("VU", "VU"),
                            ("2R", "2R"),
                            ("Bateau", "Bateau"),
                            ("Remorque", "Remorque"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Aspect",
                    models.CharField(
                        choices=[
                            ("Origine", "Origine"),
                            ("Banalisé léger", "Banalisé léger"),
                            ("Banalisé complet", "Banalisé complet"),
                            ("Banalisé amovible", "Banalisé amovible"),
                            ("Sérigraphié", "Sérigraphié"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Energie",
                    models.CharField(
                        choices=[
                            ("Essence", "Essence"),
                            ("Gazole", "Gazole"),
                            ("Electrique", "Electrique"),
                            ("Hybride", "Hybride"),
                            ("Hybride rechargeable", "Hybride rechargeable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("Constructeur", models.CharField(max_length=100)),
                ("DesignationArticle", models.CharField(max_length=100)),
                ("PrixNetTTC", models.DecimalField(decimal_places=2, max_digits=10)),
                ("PrevisionnelleLivraison", models.DateField()),
                ("EspacePieceJointe", models.BinaryField()),
                ("Commentaire", models.TextField()),
                (
                    "fk_NumeroCommande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gespar.commande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RenseignementVhPere",
            fields=[
                (
                    "pk_NumeroSerie",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("Immatriculation", models.CharField(max_length=10)),
                (
                    "Aspect",
                    models.CharField(
                        choices=[
                            ("Origine", "Origine"),
                            ("Banalisé léger", "Banalisé léger"),
                            ("Banalisé complet", "Banalisé complet"),
                            ("Sérigraphié", "Sérigraphié"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "DroitOuvertRenouvellement",
                    models.CharField(
                        choices=[("oui", "oui"), ("non", "non")], max_length=3
                    ),
                ),
                ("EspacePieceJointe", models.BinaryField()),
                ("Commentaire", models.TextField()),
                (
                    "fk_NumeroSerieFils",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gespar.renseignementvhfils",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="renseignementvhfils",
            name="fk_NumeroSeriePere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gespar.renseignementvhpere",
            ),
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "pk_NumeroCommande",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("DateReception", models.DateField()),
                (
                    "CarteGrise",
                    models.CharField(
                        choices=[
                            ("en cours", "en cours"),
                            ("envoyé", "envoyé"),
                            ("réceptionné", "réceptionné"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "CarnetBord",
                    models.CharField(
                        choices=[
                            ("en cours", "en cours"),
                            ("envoyé", "envoyé"),
                            ("réceptionné", "réceptionné"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "CarteCarburant",
                    models.CharField(
                        choices=[
                            ("en cours", "en cours"),
                            ("envoyé", "envoyé"),
                            ("réceptionné", "réceptionné"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "Statut",
                    models.CharField(
                        choices=[
                            ("Attente SAV équipementier", "Attente SAV équipementier"),
                            ("Livré au service", "Livré au service"),
                            ("En cours d'équipement", "En cours d'équipement"),
                            (
                                "Attente transfert vers SVN",
                                "Attente transfert vers SVN",
                            ),
                            (
                                "Attente transfert vers Le Chesnay",
                                "Attente transfert vers Le Chesnay",
                            ),
                            ("Prêt à livrer", "Prêt à livrer"),
                            ("Attente affectation", "Attente affectation"),
                            ("Attente documentation SGF", "Attente documentation SGF"),
                            ("Attente autre", "Attente autre"),
                            ("Attente de jugement", "Attente de jugement"),
                            ("En cours de réparation", "En cours de réparation"),
                            ("Erreur de livraison", "Erreur de livraison"),
                            ("Refusé non conforme", "Refusé non conforme"),
                            ("Attente immatriculation", "Attente immatriculation"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "StatutLivraison",
                    models.CharField(
                        choices=[
                            ("En contrôle", "En contrôle"),
                            ("En parc", "En parc"),
                            ("Non concerné", "Non concerné"),
                            ("Perçu", "Perçu"),
                            ("Incomplet", "Incomplet"),
                            ("En commande", "En commande"),
                            ("Inconnu", "Inconnu"),
                        ],
                        max_length=50,
                    ),
                ),
                ("DateMiseDisposition", models.DateField()),
                ("DateRdvRemiseCles", models.DateField()),
                ("DateRecuperationService", models.DateField()),
                (
                    "DossierCloture",
                    models.CharField(
                        choices=[("oui", "oui"), ("non", "non")], max_length=3
                    ),
                ),
                ("EspacePieceJointe", models.BinaryField()),
                ("Commentaire", models.TextField()),
                (
                    "NumeroSerieVehiculeFils",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gespar.renseignementvhfils",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtudeTechnique",
            fields=[
                (
                    "NumeroChassis",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("NumeroImmatriculation", models.CharField(max_length=100)),
                ("Constructeur", models.CharField(max_length=100)),
                ("DesignationArticle", models.CharField(max_length=100)),
                ("DateEmissionCahierCharges", models.DateField()),
                (
                    "Prestataire",
                    models.CharField(
                        choices=[
                            ("ACA", "ACA"),
                            ("UGAP", "UGAP"),
                            ("CET", "CET"),
                            ("atelier nord", "atelier nord"),
                            ("atelier sud", "atelier sud"),
                            ("atelier central", "atelier central"),
                            ("marché public", "marché public"),
                            ("hors marché", "hors marché"),
                            ("SAILMI", "SAILMI"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "StatutDossier",
                    models.CharField(
                        choices=[
                            ("en attente de validation", "en attente de validation"),
                            ("en attente de devis", "en attente de devis"),
                            ("en attente de livraison", "en attente de livraison"),
                            ("mise à disposition", "mise à disposition"),
                            ("annulé", "annulé"),
                            ("terminé", "terminé"),
                        ],
                        max_length=50,
                    ),
                ),
                ("DateTransmissionDevis", models.DateField()),
                ("DateEnvoiDevisSigneBureauFinances", models.DateField()),
                ("DateReceptionBonCommande", models.DateField()),
                ("DateEnvoiServiceFaitSigneBureauFinances", models.DateField()),
                ("DateRecuperationVHChezCarossier", models.DateField()),
                (
                    "CoutAmenagement",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("NumeroEJAménagement", models.CharField(max_length=100)),
                ("DateReceptionChezCarossier", models.DateField()),
                ("DateDebutTravauxCarossier", models.DateField()),
                ("DateRecuperationVehiculeChezCarossier", models.DateField()),
                ("EspacePieceJointe", models.BinaryField()),
                ("Commentaire", models.TextField()),
                (
                    "NumeroCommande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gespar.commande",
                    ),
                ),
                (
                    "fk_NumeroSerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gespar.renseignementvhfils",
                    ),
                ),
            ],
        ),
    ]
